// Seed data
module.exports = [
    {
        profileimg: 'https://i.imgur.com/0zMwri1.jpeg',
        name: 'Martin The Roofer',
        about: 'My moms barn needed a new roof. Sister and Brother in Law were living in it at the time. I jumped in to help redo the shingles. Not a fan of heights.',
        skills: 'Composure, balance, long arms',
        projectsimga: 'https://i.imgur.com/0u8WJuJ.jpeg',
        projectsimgb: 'https://i.imgur.com/N3VMiAk.jpeg',
        projectsimgc: 'https://i.imgur.com/JrfmK59.jpeg',
        projectsimgd: 'https://i.imgur.com/3VADWbV.jpeg',
        projectsimge: 'https://i.imgur.com/9jZxzBj.jpeg',

    },
    {
        profileimg: 'https://i.imgur.com/2qpDzKF.jpeg',
        name: 'Martin The Technical Designer',
        about: 'A friend of mine showed me the Sketchup app and the rest was history. I started using it to layout all of my custom built in, shelving, and other furniture proposals. I even used it for a couple of renovation jobs where the walls were coming down and new walls going up. It was a very helpful tool to learn and improved my ability to communicate with my clients.',
        skills: 'Drafting technical drawings',
        projectsimga: 'https://i.imgur.com/nKctJOF.jpeg',
        projectsimgb: 'https://i.imgur.com/myf7DE2.jpeg',
        projectsimgc: 'https://i.imgur.com/dQWLMIw.png',
        projectsimgd: 'https://i.imgur.com/ti1TtMU.jpg',
        projectsimge: 'https://i.imgur.com/TV14zgv.png',
    },
    {
        profileimg: 'https://i.imgur.com/GwHsxjV.png',
        name: 'Martin The Custom Storage Solution',
        about: 'An college classmate of mine is really into Tweed/Classic mens wear. He put me in touch with one of the local Brooklyn shops that he frequents. The owner had just recently moved and needed help setting up the new storefront. He had me wrap a column in plywood and install garment hanging rods.',
        skills: 'Scope Creep, Client interaction, Planning',
        projectsimga: 'https://i.imgur.com/WVNqDQB.png',
        projectsimgb: 'https://i.imgur.com/oGHUs19.png',
        projectsimgc: 'https://i.imgur.com/O9Sqetj.png',
        projectsimgd: 'https://i.imgur.com/tJ0Cq0D.jpeg',
        projectsimge: 'https://i.imgur.com/KEEaOai.jpeg',
    },
    {
        profileimg: 'https://i.imgur.com/M4MlBue.jpeg',
        name: 'Martin The Bindery Builder',
        about: 'In 2014 a friend connected me with her boss Joanna Twiggs from Twiggs Bindery in Fort Greene Brooklyn. She had moved into a larger space and had an amazing vision to build out a very tactile book bindery. We worked together to figure out exactly the design that was custom to her space as well as matched her desired color palette.',
        skills: 'Advanced Router Skills, Dovetails, Rabbets, Scarfs, all sorts of joinery, design and planning, deadline delivery of final build',
        projectsimga: 'https://i.imgur.com/Uc0plgB.jpeg',
        projectsimgb: 'https://i.imgur.com/KDzsQmM.jpeg',
        projectsimgc: 'https://i.imgur.com/6pqjgx4.jpeg',
        projectsimgd: 'https://i.imgur.com/ZXw2KsJ.jpeg',
        projectsimge: 'https://i.imgur.com/kYg4vhl.jpeg',
        projectsimgf: 'https://i.imgur.com/s2pLuRb.jpeg',
    },
]
